"""user_media user idea unique constraint

Revision ID: 21b8cb966c4f
Revises: eefb4c388ba4
Create Date: 2025-08-22 15:31:41.640766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b8cb966c4f'
down_revision: Union[str, None] = 'eefb4c388ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_media_user_id', table_name='user_media')
    op.create_unique_constraint('uq_user_media_user_id', 'user_media', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_media_user_id', 'user_media', type_='unique')
    op.create_index('ix_user_media_user_id', 'user_media', ['user_id'], unique=False)
   
    # ### end Alembic commands ###
