"""Set default tier to FREE

Revision ID: 45cbe920d8e9
Revises: a597122ea703
Create Date: 2025-08-05 13:00:52.725707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45cbe920d8e9'
down_revision: Union[str, None] = 'a597122ea703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "userss",                # table name
        "tier_level",            # column name
        existing_type=sa.Enum(
            'HOBBY', 'ENTERPRISE', 'FREE', name='tierlevel'
        ),
        server_default=sa.text("'FREE'"),
        existing_nullable=False,
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "userss",
        "tier_level",
        existing_type=sa.Enum(
            'HOBBY', 'ENTERPRISE', 'FREE', name='tierlevel'
        ),
        server_default=sa.text("'HOBBY'"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
