"""add updated at url shortener

Revision ID: 7d9d74ce04a9
Revises: 45cbe920d8e9
Create Date: 2025-08-14 11:12:25.072532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9d74ce04a9'
down_revision: Union[str, None] = '45cbe920d8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_shortener', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True,server_default=sa.func.now(), onupdate=sa.func.now()))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('url_shortener', 'updated_at')
    # ### end Alembic commands ###
