"""Add new tier level FREE

Revision ID: a597122ea703
Revises: 801cf01b182d
Create Date: 2025-08-05 12:36:41.919050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a597122ea703'
down_revision: Union[str, None] = '801cf01b182d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.execute("ALTER TYPE tierlevel ADD VALUE IF NOT EXISTS 'FREE';")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
