"""add user media table

Revision ID: eefb4c388ba4
Revises: 7d9d74ce04a9
Create Date: 2025-08-21 17:39:14.210808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefb4c388ba4'
down_revision: Union[str, None] = '7d9d74ce04a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_img_path', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_img_path', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['userss.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_media_user_id'), 'user_media', ['user_id'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.drop_index(op.f('ix_user_media_user_id'), table_name='user_media')
    op.drop_table('user_media')
    # ### end Alembic commands ###
